url= "http://www.locohistory.org/blog/albemarle"
name= "LoCoHistory"
description = "One faces the future with one's past - Pearl S. Buck"
baseurl = "http://www.locohistory.org/"
languageCode = "en-us"
title = "LoCoHistory"
# disqusShortname = "spf13"
# googleAnalytics = ""
paginate = 20
theme = "hugo-icarus-theme"
[params]
    # Tell me who you're
    author = "John Doe"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    # Format dates with Go's time formating
    date_format = "Jan 2, 2006"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = true
    label  = "Albemarle"
    link   = "/categories/albemarle/"

[[params.menu]]
    before = true
    label  = "Amherst"
    link   = "/categories/amherst/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    instagram       = ""
    tumblr          = ""
    linkedin        = ""
    pinterest       = ""
    facebook        = ""
    twitter         = "DrLynnRainville"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = false
    tag_cloud = false
